In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import tweepy
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
nltk.download('punkt')
from sklearn.feature_extraction.text import CountVectorizer
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASReddy\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASReddy\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASReddy\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [2]:
df=pd.read_csv('dataset.csv',encoding='Latin-1')

In [3]:
df.head(10)

Tweets  label
0   Dear Media, The Nation wants to know about st...      1
1   No. Like they've been saying all along. If yo...     -1
2   Spain’s second wave: Worrying that the report...      0
3   Congrats on the marriage  thing. Hey Derby We...      1
4   We are really in September . Wow. Still livin...      1
5  The SoS for Health has to act with absolute ne...      1
6   Will Twitter and CNN Attack and Take Down FOX...     -1
7  With Fans Forbidden Due To COVID-19, A Noticea...     -1
8   More deaths by suicide in Ireland this week t...      1
9   Of course it will spike.  The people who go t...      1

In [4]:
df.isnull().sum()

Tweets    0
label     0
dtype: int64

In [5]:
wordnet=WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

In [6]:
def change_text(a):
    a=str(a)
    text=re.sub('[^a-zA-Z]',' ',a)
    text=text.lower()
    text=nltk.word_tokenize(text)
    text=[wordnet.lemmatize(word) for word in text if word not in stop_words]
    text=' '.join(text)
    return text

In [7]:
df['tweet']=df['Tweets'].apply(change_text)
df.head()

Tweets  label  \
0   Dear Media, The Nation wants to know about st...      1   
1   No. Like they've been saying all along. If yo...     -1   
2   Spain’s second wave: Worrying that the report...      0   
3   Congrats on the marriage  thing. Hey Derby We...      1   
4   We are really in September . Wow. Still livin...      1   

                                               tweet  
0  dear medium nation want know status covid case...  
1  like saying along illness like diabetes high r...  
2  spain second wave worrying report say median a...  
3  congrats marriage thing hey derby weekend stea...  
4            really september wow still living covid

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X1= vectorizer.fit_transform(df['tweet'])
y=df['label']

In [9]:
import sklearn
x_train,x_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=42)
model = sklearn.linear_model.LogisticRegression(penalty="l2", C=0.1)
model.fit(x_train, y_train)

LogisticRegression(C=0.1)

In [10]:
prediction=model.predict(x_test)

In [11]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [12]:
cf_matrix=confusion_matrix(y_test,prediction)
print(cf_matrix)

[[113   2   0]
 [ 85  13   0]
 [ 80   3   0]]


In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,prediction))

0.42567567567567566
